import type { Config } from 'prettier';

const config = {
  printWidth: 120,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSameLine: false,
  bracketSpacing: true,
  arrowParens: 'always',
  requirePragma: false,
  insertPragma: false,
  proseWrap: 'never',
  plugins: [import.meta.resolve('prettier-plugin-packagejson')],
  packageSortOrder: [
    'name',
    'version',
    'description',
    'private',
    'license',
    'publishConfig',
    'packageManager',
    'keywords',
    'homepage',
    'bugs',
    'repository',
    'author',
    'scripts',
    'type',
    'sideEffects',
    'files',
    'main',
    'module',
    'types',
    'exports',
    'imports',
    'prettier',
    'dependencies',
    'devDependencies',
    'peerDependencies',
    'peerDependenciesMeta',
    'optionalDependencies',
  ],
} as const satisfies Config;

export default config;
